image:
  - Visual Studio 2022

version: 18.0.0-{build}

skip_tags: false

platform: x64
configuration: Release

clone_folder: C:\cargo-update

environment:
  matrix:
    - TOOLCHAIN: stable
    - TOOLCHAIN: 1.82.0

install:
  - set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%;C:\Users\appveyor\.cargo\bin
  - bash -lc "pacman --noconfirm -Syyu"
  - bash -lc "pacman --noconfirm -Syyu"
  - bash -lc "pacman --noconfirm -S mingw-w64-x86_64-toolchain zip"
  -
  - mkdir target\release\deps
  - cp C:\Windows\System32\ntdll.dll target\release\deps
  -
  - curl -SL https://win.rustup.rs/ -oC:\rustup-init.exe
  - C:\rustup-init.exe -y --default-host="x86_64-pc-windows-gnu" --default-toolchain="%TOOLCHAIN%"

build: off
build_script:
  - cargo build --verbose --release
  -
  - mkdir cargo-update-v18.0.0
  - cp target\release\cargo-install-update.exe target\release\cargo-install-update-config.exe cargo-update-v18.0.0\
  - strip --strip-all --remove-section=.comment --remove-section=.note cargo-update-v18.0.0/cargo-install-update.exe cargo-update-v18.0.0/cargo-install-update-config.exe
  - zip -9r cargo-update-v18.0.0.zip cargo-update-v18.0.0

test: off
test_script:
  - cargo test --verbose --release

artifacts:
  - path: cargo-update-v18.0.0.zip

deploy:
  provider: GitHub
  artifact: cargo-update-v18.0.0.zip
  auth_token:
    secure: FNqRpbXgjNh7VrtHCIGadt7Pwv9HGq4kyUCQFueRLJvQCCWWWgko3PwiZvYlaAEG
  on:
    appveyor_repo_tag: true

notifications:
  - provider: Email
    to:
      - nabijaczleweli@gmail.com
    on_build_status_changed: true
